[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "analyzeAudio"
dynamic = ["version"]
readme = "README.md"
dependencies = [
    "cachetools",
    "librosa",
    "numpy",
    "torch",
    "torchmetrics[audio]",
    "tqdm",
    "Z0Z_tools @ git+https://github.com/hunterhogan/Z0Z_tools.git",
]

[project.urls]
"Homepage" = "https://github.com/hunterhogan/analyzeAudio"

[tool.setuptools.packages.find]
where = ["."]
include = ["*"]

[tool.setuptools.dynamic]
version = { attr = "analyzeAudio.__version__" }
