[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "analyzeAudio"
version = "0.0.11"
readme = "README.md"
authors = [
    {name = "Hunter Hogan", email = "HunterHogan@pm.me"}
]
dependencies = [
    "cachetools",
    "librosa",
    "numpy",
    "torch",
    "torchmetrics[audio]",
    "tqdm",
    "Z0Z-tools",
]

[project.urls]
"Homepage" = "https://github.com/hunterhogan/analyzeAudio"

[tool.setuptools.packages.find]
where = ["."]
include = ["*"]
